### ISSUE TITLE
Support canceling routes on navigate

### ISSUE THREAD

**Issue by jmeas** [jmeas/backbone.base-router#22]
Canceling routes should be possible, but the interaction between the BB.History and the registered routes makes this a non-trivial task.

The registered Route should determine whether it can be canceled or not. And the act of canceling needs to happen **before** history updates the URI. Yet the Router sends over a *callback* that does not have knowledge of the linked object...only the Router ever knows about the link.

I might need to rewrite history/routing altogether to do this.

**Comment by Anachron** [comment]
+1 

This should be doable with a beforeNavigate event that sends a false for cancelled routes.

**Comment by jmeas** [comment]
If the router manages everything separately from history, then this would be easy to add. In this world, the Router wouldn't even register callbacks for routes: it would simply use Backbone.history to update the URL.

I think this is tha way to go.

**Comment by jmeas** [comment]
Gonna close this as out-of-scope for base router. The system I'm building, described briefly above, will solve this problem.
