### ISSUE TITLE
Support route removal and insert-at

### ISSUE THREAD

**Issue by ianmstew** [jmeas/backbone.base-router#23]
An API for more flexible dynamically-constructed routers would be quite powerful.  This would enable subclasses to implement a modular router paradigm while keeping order intact when it counts, such as the soft-404 handler.  The implementation would essentially boil down to splicing on the undocumented Backbone.history.handlers array.  Or, like you mention in #22, the alternative may be a rewrite of Backbone.history. 

Possible use case:
- Allow for dynamic registering/deregistering routes without conflicting with a catch-all terminal route, such as a soft-404 handler

Possible API
- Backbone.history.insertBefore(route, referenceRoute)
- Backbone.history.insertAfter(route, referenceRoute)
- Backbone.history.insertAt(route, index)
- Backbone.history.remove(route or index)

Note that route removal and insert-at could be rendered unnecessary if this library departs from Backbone.History "callback order" entirely.  Perhaps that is the question that should be answered first, whether or not this library will become "an effort to rewrite Backbone.history" after all.

**Comment by Anachron** [comment]
I've been thinking to use dependency based object storing, maybe in a linked list or something. 

You could first load your app and then insert your module routes without having to worry where it will stored into.

**Comment by jmeas** [comment]
@anachron, can you elaborate?

**Comment by Anachron** [comment]
@jmeas sure!

If you use a linked list or graph you can store your dependencies. Then when you load or unload modules you read the dependencies to insert the routes before or after the dependencies, depending on the definition. When you unload you will remove the node that has been linked to the unloading module.

All of this should be optional, of course.

**Comment by jmeas** [comment]
Interesting @anachron. I'm going to close this issue because I think it's beyond the scope of the router to fix Backbone's route resolution mechanism. I think such a change would get into overriding History. I'm also still not that big a fan of skirting around the issue by removing / inserting routes into the handlers array.

I'm planning a new system for routing that solves all of these problems, and more. Base Router is a good library to use in the meantime tho'.
