### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by jeffijoe** [jmeas/backbone.base-router#31]
Same issue as with [Intercept](https://github.com/jmeas/backbone.intercept/issues/26), the outdated dependencies are screwing up Webpack builds.

**Comment by jmeas** [comment]
PRs welcome!

:stuck_out_tongue:

**Comment by jeffijoe** [comment]
Will probably be on sunday - let me know if you did it yourself before then. :)

**Comment by jmeas** [comment]
Released as 1.1.0!

Thanks @jeffijoe !
